# Generated by Django 6.0.7 on 2026-07-08 09:52

import django.db.models.deletion
import equipment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(help_text='Unique asset tag / identifier, e.g. BHEL-TUR-001', max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('machine_type', models.CharField(choices=[('TURBINE', 'Turbine'), ('MOTOR', 'Motor'), ('PUMP', 'Pump'), ('BOILER', 'Boiler'), ('TRANSFORMER', 'Transformer'), ('COMPRESSOR', 'Compressor'), ('GENERATOR', 'Generator'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('department', models.CharField(choices=[('BOILER_PLANT', 'Boiler Plant'), ('TURBINE_PLANT', 'Turbine Plant'), ('ELECTRICAL', 'Electrical'), ('FABRICATION', 'Fabrication'), ('QUALITY_CONTROL', 'Quality Control'), ('MAINTENANCE', 'Maintenance'), ('R_AND_D', 'R&D'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('location', models.CharField(blank=True, help_text='Physical location / plant bay / floor', max_length=150)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('installation_date', models.DateField(validators=[equipment.models.validate_not_future_date])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('INACTIVE', 'Inactive'), ('DECOMMISSIONED', 'Decommissioned')], default='ACTIVE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='equipment_m_status_5122c3_idx'), models.Index(fields=['department'], name='equipment_m_departm_42bb96_idx'), models.Index(fields=['machine_type'], name='equipment_m_machine_4db930_idx')],
            },
        ),
    ]
