# Generated by Django 6.0.7 on 2026-07-08 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(help_text='e.g. Bearing Temperature, Vibration, RPM', max_length=100)),
                ('unit', models.CharField(choices=[('C', '°C'), ('F', '°F'), ('MM_S', 'mm/s (vibration)'), ('BAR', 'bar (pressure)'), ('PSI', 'psi (pressure)'), ('RPM', 'RPM'), ('A', 'A (current)'), ('V', 'V (voltage)'), ('PERCENT', '%'), ('HZ', 'Hz'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('normal_min', models.FloatField(help_text='Lower bound of the normal operating range')),
                ('normal_max', models.FloatField(help_text='Upper bound of the normal operating range')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_definitions', to='equipment.machine')),
            ],
            options={
                'ordering': ['machine', 'sensor_name'],
                'unique_together': {('machine', 'sensor_name')},
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('recorded_at', models.DateTimeField(help_text='When the reading was taken')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('CSV', 'CSV Upload'), ('EXCEL', 'Excel Upload')], default='MANUAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_readings', to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensordefinition')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['sensor', 'recorded_at'], name='sensors_sen_sensor__e1a858_idx'), models.Index(fields=['recorded_at'], name='sensors_sen_recorde_8af75c_idx')],
            },
        ),
    ]
