# Generated by Django 6.0.7 on 2026-07-10 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode_default', models.BooleanField(default=False, help_text='Theme to use when this browser has no saved preference yet.')),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Receive email alerts (maintenance assignments, critical risk predictions) in addition to in-app notifications.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
